
import React from 'react';
import industry from './industry.mp4';
import './style/BackgroundInformation.css';

const BackgroundInformation = () => {
    return (
        <div className="background-information">
            <video src={industry} autoPlay loop muted />
            <div className="background-container">
                <h2>Understanding Waste and Its Impact</h2>
                <p>
                    Waste management is a critical component in addressing climate change and promoting sustainability. Effective waste management practices, such as recycling, waste prevention, and landfill gas capture, can significantly reduce greenhouse gas emissions. For example, cutting waste generation to 1990 levels could reduce emissions by 18 million metric tons of carbon equivalent (MMTCE), while increasing the national recycling rate from 30% to 35% could save another 10 MMTCE. Programs like the EPA's WasteWise and Pay-As-You-Throw incentivize waste reduction and recycling, making substantial contributions to mitigating climate change.
                </p>
                <h2>The Significance of Medical Waste Management</h2>
                <p>
                    Medical waste, generated by healthcare facilities like hospitals, clinics, and laboratories, requires specialized handling due to its potentially hazardous nature. This type of waste includes infectious materials, sharps, chemicals, and pharmaceuticals. Proper management of medical waste is essential to prevent the spread of infections, protect healthcare workers, and ensure environmental safety. The decomposition of organic medical waste in landfills produces methane, a potent greenhouse gas. Therefore, reducing and properly disposing of medical waste is crucial for both public health and environmental protection.
                </p>
                <h2>Importance and Affected Parties</h2>
                <p>
                    Medical waste management is vital for protecting patients, healthcare staff, and the broader community. Improper disposal can lead to injuries, infections, and environmental contamination. Effective waste management practices safeguard medical personnel from exposure to hazardous materials and prevent the spread of diseases. Additionally, it reduces the ecological footprint of healthcare facilities by minimizing harmful emissions and promoting sustainability.
                </p>
                <h2>UCSD Medical Center's Role</h2>
                <p>
                    UCSD Medical Center has waste management strategies to enhance sustainability and protect public health. By integrating practices such as recycling, proper disposal of hazardous materials, and waste reduction programs, UCSD Medical Center aims to minimize its environmental impact. The institution also focuses on educating staff and patients about the importance of proper waste disposal and the role they play in maintaining a safe and sustainable environment.
                </p>
            </div>
        </div>
    );
};

export default BackgroundInformation;
